### ISSUE TITLE
Error when running `export`: uninitialized constant Rainforest::Test (NameError)

### ISSUE THREAD

**Issue by Taytay** [rainforestapp/rainforest-cli#230]
I've installed the gem (via Gemfile/bundler), and am now experimenting with it, and I got this error:
```
$ rainforest export --token MY_TOKEN
/home/vagrant/.rvm/gems/ruby-2.3.2/gems/rainforest-cli-1.2.0/lib/rainforest/cli/test_importer.rb:37:in `export': uninitialized constant Rainforest::Test (NameError)
	from /home/vagrant/.rvm/gems/ruby-2.3.2/gems/rainforest-cli-1.2.0/lib/rainforest/cli.rb:42:in `start'
	from /home/vagrant/.rvm/gems/ruby-2.3.2/gems/rainforest-cli-1.2.0/bin/rainforest:7:in `<top (required)>'
	from /home/vagrant/.rvm/gems/ruby-2.3.2/bin/rainforest:22:in `load'
	from /home/vagrant/.rvm/gems/ruby-2.3.2/bin/rainforest:22:in `<main>'
	from /home/vagrant/.rvm/gems/ruby-2.3.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/vagrant/.rvm/gems/ruby-2.3.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by Taytay** [comment]
I think I'm on an old version, as evidenced by the rainforest-cli-1.2.0. I will figure this out.
