### ISSUE TITLE
rainforest validate does not validate start_uri. Fails on upload

### ISSUE THREAD

**Issue by newtonik** [rainforestapp/rainforest-cli#244]
When start_uri is missing it passes the validation step and fails on uploads. See stack trace. 

```Any other versions on the specified services will receive zero traffic.
Uploading Rainforest tests
I, [2017-01-20T23:37:23.558507 #24463]  INFO -- : Validating parsing errors...
I, [2017-01-20T23:37:23.558638 #24463]  INFO -- : Validating embedded test IDs...
I, [2017-01-20T23:37:23.558722 #24463]  INFO -- : Fetching test data from server...
I, [2017-01-20T23:37:23.751873 #24463]  INFO -- : Fetch complete.
I, [2017-01-20T23:37:23.756608 #24463]  INFO -- : 
I, [2017-01-20T23:37:23.756664 #24463]  INFO -- : [VALID]
I, [2017-01-20T23:37:23.756840 #24463]  INFO -- : Syncing new tests...
bundler: failed to load command: rainforest (/home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/bin/rainforest)
Rainforest::ApiError: {"error":"Start uri parameter is missing"}
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/rainforest-2.1.0/lib/rainforest/apibits/api_method.rb:33:in `rescue in execute'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/rainforest-2.1.0/lib/rainforest/apibits/api_method.rb:25:in `execute'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/rainforest-2.1.0/lib/rainforest/apibits/api_client.rb:18:in `execute'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/rainforest-2.1.0/lib/rainforest/endpoints/tests_endpoint.rb:43:in `create'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/rainforest-2.1.0/lib/rainforest/resources/test.rb:45:in `create'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/rainforest-cli-1.11.0/lib/rainforest_cli/uploader.rb:86:in `upload_empty_test'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/rainforest-cli-1.11.0/lib/rainforest_cli/uploader.rb:23:in `block in upload'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/rainforest-cli-1.11.0/lib/rainforest_cli/uploader.rb:63:in `call'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/rainforest-cli-1.11.0/lib/rainforest_cli/uploader.rb:63:in `block in each_in_parallel'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/parallel-1.10.0/lib/parallel.rb:462:in `call'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/parallel-1.10.0/lib/parallel.rb:462:in `call_with_index'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/parallel-1.10.0/lib/parallel.rb:322:in `block (2 levels) in work_in_threads'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/parallel-1.10.0/lib/parallel.rb:473:in `with_instrumentation'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/parallel-1.10.0/lib/parallel.rb:321:in `block in work_in_threads'
  /home/ubuntu/deployment/vendor/bundle/ruby/2.2.0/gems/parallel-1.10.0/lib/parallel.rb:203:in `block (2 levels) in in_threads'
```

**Comment by ukd1** [comment]
@newtonik thanks for this! @epaulet could you take a look at this or figure out who should look at this?
