### ISSUE TITLE
rainforest mobile-upload failing on TRAVIS_CI

### ISSUE THREAD

**Issue by milantechholding** [rainforestapp/rainforest-cli#356]
### Approach :
I have integrated `rainforest-cli` with fastlane and created a lane of it.
It works completely fine with local terminal i.e. my local machine, but it failed by builds on "TRAVIS_CI"

I am using this command for build `rainforest mobile-upload --site-id xxxxx --environment-id xxxxx /Path/To/My/App.app.zip` I have already stored token in environment variable `RAINFOREST_API_TOKEN `.

### Error :
`[!] Exit status of command 'rainforest mobile-upload -site-id XXXXX -environment-id XXXXX /Path/To/My/App.app.zip' was 3 instead of 0`

Any help would be appreciated.

**Comment by shosti** [comment]
@milantechholding thanks for the report. I think there's not quite enough information to debug, can you try:

- [ ] Check `rainforest-cli --version` on both your local machine and on travis
- [ ] Add the `--skip-update --debug` options on both travis and locally

If you can post the results here (scrubbing out anything sensitive, of course) that would be very helpful.

**Comment by milantechholding** [comment]
**Input :**
`$ rainforest --version`
**Output :**
`$ rainforest version 2.8.12 - stable channel - build: 61415d8d`

**Input :**
`rainforest mobile-upload --skip-update --debug --site-id XXXXX --environment-id XXXXX /Path/To/My/App.app.zip`
**Output :**
Exit status of command 'rainforest mobile-upload --skip-update --debug --site-id XXXXX --environment-id XXXXX /Path/To/My/App.app.zip' was 3 instead of 0.
```

(FastlaneCore::Interface::FastlaneShellError)
2019/05/13 10:23:46 No help topic for 'mobile-upload'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/helper/sh_helper.rb:16:in `sh_no_action'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/fast_file.rb:187:in `block in sh'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/fast_file.rb:186:in `sh'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/fast_file.rb:181:in `sh'
	from lanes/HelperLanesFastfile.rb:189:in `block in parsing_binding'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from lanes/NightlyFastfile.rb:68:in `block in parsing_binding'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from lanes/NightlyFastfile.rb:47:in `block (2 levels) in parsing_binding'
	from lanes/NightlyFastfile.rb:46:in `each'
	from lanes/NightlyFastfile.rb:46:in `block in parsing_binding'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/travis/.rvm/gems/ruby-2.3.4/gems/fastlane-2.107.0/bin/fastlane:23:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.3.4/bin/fastlane:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.3.4/bin/fastlane:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
```


**Note :** Adding --debug flag not adding any extra verbose.

**Comment by shosti** [comment]
Sorry for the delay--can you try getting `rainforest --version` to run on Travis?

**Comment by milantechholding** [comment]
> **Input :**
> `$ rainforest --version`
> **Output :**
> `$ rainforest version 2.8.12 - stable channel - build: 61415d8d`


Hi @shosti , I have already provided that earlier it is `$ rainforest version 2.8.12 - stable channel - build: 61415d8d`

Hope this helps.

**Comment by jbarber** [comment]
Hi @milantechholding - mobile upload was added in 2.11.0, if you update the CLI to the latest version, everything should work.

**Comment by milantechholding** [comment]
Hi @jbarber,
I think after using latest version issue seems resolved. I am using latest version **2.13.0**

But this problem happens because whenever we download the new version via homebrew it always downloads **2.8.12** because it is explicitly stated in this file: **https://github.com/rainforestapp/homebrew-public/blob/master/rainforest-cli.rb**

I had managed it by writing two commands in CLI,
```
- brew install rainforestapp/public/rainforest-cli
- rainforest update
```

I wish/suggest if we have appropriate version there.
Thanks,
Milan
