### ISSUE TITLE
Syntax errors in v1.2.1

### ISSUE THREAD

**Issue by jivinivan** [rainforestapp/rainforest-cli#65]
We've started receiving syntax errors since v1.2.1 was released. Looks like it's happening when we try to upload new tests. 

```
/home/ubuntu/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require': /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rainforest-cli-1.2.1/lib/rainforest/cli/http_client.rb:36: syntax error, unexpected tLABEL (SyntaxError)
    def get(url, body = {}, retries_on_failures: false)
                                                ^
/home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rainforest-cli-1.2.1/lib/rainforest/cli/http_client.rb:94: syntax error, unexpected keyword_end, expecting $end
	from /home/ubuntu/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rainforest-cli-1.2.1/lib/rainforest/cli.rb:9:in `<top (required)>'
	from /home/ubuntu/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/gems/rainforest-cli-1.2.1/bin/rainforest:5:in `<top (required)>'
	from /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/bin/rainforest:22:in `load'
	from /home/ubuntu/.rvm/gems/ruby-1.9.3-p448/bin/rainforest:22:in `<main>'
```

**Comment by epaulet** [comment]
Is this issue still happening in 1.2.1?

**Comment by epaulet** [comment]
Closing for now. We'll open new issue if this problem resurfaces in version >= 1.30.
